# Railway Configuration
# This file tells Railway how to build and run your Python app with uv

[build]
builder = "NIXPACKS"

[build.env]
UV_SYSTEM_PYTHON = "1"

[deploy]
startCommand = "uv run citation-verifier-remote"
